### ISSUE TITLE
Pregunta sobre listdb_create

### ISSUE THREAD

**Issue by ivanvladimir** [gibranfp/Sampled-MinHashing#1]
listdb_create recibe dos parámetros: size and dim, pero no usa dim... ya siempre lo asigna a 0, está bien eso?

   ListDB listdb_create(uint size, uint dim)
   {
      ListDB listdb;
       listdb.size = size;
       listdb.dim = 0;
       listdb.lists = (List *) calloc(size, sizeof(List));
       return listdb;
   }

**Comment by gibranfp** [comment]
No, está mal, ya lo corregí. ¡Gracias!
